import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Language = "en" | "te";

const translations: Record<Language, Record<string, string>> = {
  en: {
    // App
    "app.name": "SeniorSphere",
    "app.tagline": "Connect with your community",
    "app.loading": "Loading...",
    "app.user": "User",
    "app.friend": "Friend",
    "app.anonymous": "Anonymous",
    "app.justNow": "Just now",
    "app.minutesAgo": "{count}m ago",
    "app.hoursAgo": "{count}h ago",
    "app.daysAgo": "{count}d ago",

    // Roles
    "role.senior": "Senior Citizen",
    "role.family_member": "Family Member",
    "role.moderator": "Community Moderator",
    "role.admin": "Administrator",
    "role.badge.moderator": "Moderator",
    "role.badge.family": "Family",
    "role.badge.admin": "Admin",

    // Nav
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.community": "Community",
    "nav.events": "Events",
    "nav.skills": "Skills",
    "nav.help": "Help",
    "nav.messages": "Messages",
    "nav.helpRequests": "Help Requests",
    "nav.profile": "Profile",
    "nav.logout": "Log Out",

    // Dashboard
    "dashboard.hello": "Hello",
    "dashboard.whatToDo": "What would you like to do today?",
    "dashboard.checkin": "Daily Check-in",
    "dashboard.checkedIn": "✓ Checked in today!",
    "dashboard.communityStats": "Community Stats",
    "dashboard.members": "Members",
    "dashboard.upcomingEvents": "Upcoming Events",
    "dashboard.helpRequests": "Help Requests",
    "dashboard.skillsShared": "Skills Shared",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.createEvent": "Create Event",
    "dashboard.createEventDesc": "Organize a walk or meetup",
    "dashboard.shareSkill": "Share Skill",
    "dashboard.shareSkillDesc": "Teach something you know",
    "dashboard.askHelp": "Ask for Help",
    "dashboard.askHelpDesc": "Request assistance",
    "dashboard.createPost": "Create Post",
    "dashboard.createPostDesc": "Share with the community",
    "dashboard.viewEvents": "View Events",

    // Events
    "events.title": "Events",
    "events.create": "Create",
    "events.noEvents": "No events yet",
    "events.noEventsDesc": "Create the first event for your community!",
    "events.createEvent": "Create Event",
    "events.eventTitle": "Event Title",
    "events.description": "Description",
    "events.date": "Date",
    "events.time": "Time (optional)",
    "events.location": "Location",
    "events.cancel": "Cancel",
    "events.joined": "Joined",
    "events.join": "Join",
    "events.by": "By",
    "events.attendees": "attendees",
    "events.remove": "Remove",

    // Skills
    "skills.title": "Skills Exchange",
    "skills.offer": "Offer Skill",
    "skills.noSkills": "No skills shared yet",
    "skills.noSkillsDesc": "Be the first to share a skill!",
    "skills.offerSkill": "Offer a Skill",
    "skills.skillTitle": "Skill Title",
    "skills.description": "Description",
    "skills.cancel": "Cancel",
    "skills.learning": "Learning",
    "skills.learnThis": "Learn This",
    "skills.taughtBy": "Taught by",
    "skills.learners": "learners",
    "skills.remove": "Remove",

    // Help
    "help.title": "Help Requests",
    "help.create": "Request Help",
    "help.noRequests": "No help requests",
    "help.noRequestsDesc": "Everyone seems to be doing well!",
    "help.createRequest": "Request Help",
    "help.whatHelp": "What do you need help with?",
    "help.category": "Category",
    "help.urgency": "Urgency",
    "help.locationOpt": "Location (optional)",
    "help.cancel": "Cancel",
    "help.volunteer": "Volunteer",
    "help.volunteered": "Volunteered",
    "help.volunteers": "volunteers",
    "help.pending": "Pending",
    "help.assigned": "Assigned",
    "help.completed": "Completed",
    "help.urgencyLow": "Low",
    "help.urgencyMedium": "Medium",
    "help.urgencyHigh": "High",
    "help.catGeneral": "General",
    "help.catMedical": "Medical",
    "help.catTransport": "Transport",
    "help.catGroceries": "Groceries",
    "help.catTechnology": "Technology",

    // Community
    "community.title": "Community",
    "community.activity": "Activity",
    "community.flagged": "Flagged",
    "community.showAll": "Show All",
    "community.shareSomething": "Share something with your community...",
    "community.aiModeration": "🤖 AI moderation active",
    "community.post": "Post",
    "community.posting": "Posting...",
    "community.noPosts": "No posts yet",
    "community.noPostsDesc": "Be the first to share something!",
    "community.noFlagged": "No flagged posts",
    "community.healthy": "Community is healthy! 🎉",
    "community.report": "Report",
    "community.dismissFlag": "✓ Dismiss Flag",
    "community.remove": "Remove",

    // Profile
    "profile.title": "Profile",
    "profile.editProfile": "Edit Profile",
    "profile.save": "Save",
    "profile.cancel": "Cancel",
    "profile.emergencyContact": "Emergency Contact",
    "profile.contactName": "Contact name",
    "profile.phone": "Phone number",
    "profile.emailOptional": "Email for family member connection",
    "profile.relationship": "Relationship",
    "profile.saveContact": "Save Contact",
    "profile.familyMembers": "Family Members",
    "profile.connectedFamily": "Connected family member",
    "profile.inviteDesc": "Share the invite link below with your family member. They must sign up as \"Family Member\" using the same email saved in your emergency contact.",
    "profile.copyInvite": "Copy Invite Link",
    "profile.moderatorInfo": "Moderator Info",
    "profile.community": "Community",
    "profile.role": "Role",
    "profile.familyInfo": "Family Info",
    "profile.familyInfoDesc": "Your profile details are synced with your connected senior.",
    "profile.settings": "Settings",
    "profile.noCommunity": "No community",

    // Login
    "login.fullName": "Full Name",
    "login.email": "Email",
    "login.password": "Password",
    "login.iAm": "I am a:",
    "login.joinCommunity": "Join a Community",
    "login.communitySelectHelp": "Choose an existing community or request a new one if yours is missing.",
    "login.selectCommunity": "Select a community",
    "login.requestNewCommunity": "Request New Community",
    "login.communityName": "Community name (e.g. Sunrise Residency)",
    "login.city": "City",
    "login.area": "Area / Locality",
    "login.additionalNotes": "Additional notes (optional)",
    "login.communityRequestHelp": "Your request will be counted with matching requests from the same area. Admin approval starts at 5 requests.",
    "login.signUp": "Sign Up",
    "login.logIn": "Log In",
    "login.pleaseWait": "Please wait...",
    "login.alreadyAccount": "Already have an account?",
    "login.noAccount": "Don't have an account?",
    "login.seniorDesc": "I'm a senior looking to connect",
    "login.familyDesc": "I want to monitor a loved one",
    "login.moderatorDesc": "I help manage the community",

    // Emergency
    "emergency.title": "Emergency Contact",
    "emergency.callNow": "Call Now",
    "emergency.cancel": "Cancel",
    "emergency.familyDoctor": "Family Doctor",
    "emergency.loading": "Loading...",
    "emergency.noContact": "No emergency contact",
    "emergency.addContact": "Add a contact in Profile",

    // Language
    "lang.switch": "తెలుగు",

    // Header
    "header.toggleTheme": "Toggle theme",
    "header.switchLanguage": "Switch language",
    "header.install": "Install",
    "header.installApp": "Install app",
    "header.installDismissed": "Install prompt dismissed.",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark all read",
    "notifications.noNotifications": "No notifications yet",

    // Messages
    "messages.loading": "Loading...",
    "messages.loginRequired": "Please log in to view messages.",
    "messages.empty": "No messages yet.",
    "messages.emptyHello": "No messages yet. Say hello!",
    "messages.emptyHint": "Messages will appear when you connect with someone through skills, events, or help requests.",
    "messages.typePlaceholder": "Type a message...",
    "messages.contextSkill": "Skill",
    "messages.contextHelpRequest": "Help Request",
    "messages.contextEvent": "Event",

    // Speech
    "speech.readAloud": "Read aloud",
    "speech.stop": "Stop",
    "speech.voiceInput": "Voice input",
    "speech.listening": "Listening...",

    // Common
    "common.edit": "Edit",
    "common.save": "Save",
    "common.saved": "Saved!",
    "common.cancel": "Cancel",

    // Not found
    "notFound.message": "Oops! Page not found",
    "notFound.home": "Return to Home",

    // Admin
    "admin.loading": "Loading admin dashboard...",
    "admin.refreshed": "Dashboard refreshed.",
    "admin.loadFailed": "Failed to load admin dashboard.",
    "admin.communityApproved": "Community approved and moderator created.",
    "admin.approveFailed": "Could not approve request.",
    "admin.communityRejected": "Community request rejected.",
    "admin.rejectFailed": "Could not reject request.",
    "admin.moderatorReassigned": "Moderator reassigned.",
    "admin.reassignFailed": "Could not reassign moderator.",
    "admin.replacementCreated": "Replacement moderator created.",
    "admin.replacementFailed": "Could not create replacement moderator.",
    "admin.communityDeleted": "Deleted {community}.",
    "admin.deleteFailed": "Could not delete community.",
    "admin.copied": "{label} copied.",
    "admin.copyFailed": "Could not copy {label}.",
    "admin.title": "Admin Dashboard",
    "admin.subtitle": "Manage communities, users, and platform settings",
    "admin.refresh": "Refresh",
    "admin.totalCommunities": "Total Communities",
    "admin.totalUsers": "Total Users",
    "admin.pendingRequests": "Pending Requests",
    "admin.communityRequestsTitle": "Community Requests",
    "admin.noPendingRequests": "No pending community requests.",
    "admin.peopleRequested": "{count} people requested",
    "admin.approve": "Approve",
    "admin.reject": "Reject",

    // Skills
    "skills.requestSkill": "Skill Request",
    "skills.joined": "Joined ✓",
    "skills.failed": "Failed: ",
    "skills.ownListing": "This is your own listing!",
    "skills.alreadyJoined": "Already joined!",
    "skills.request": "Request",
    "skills.offeredTab": "Offered Skills",
    "skills.requestsTab": "Skill Requests",
    "skills.requestFormTitle": "Request a Skill",
    "skills.requestTitlePlaceholder": "What skill do you want to learn?",
    "skills.requestDescPlaceholder": "Describe what you'd like to learn...",
    "skills.submitRequest": "Submit Request",
    "skills.noRequests": "No skill requests yet",
    "skills.noRequestsDesc": "Be the first to request a skill you'd like to learn!",
    "skills.requestBadge": "Skill Request",
    "skills.offeredBadge": "Skill Offered",
    "skills.requestedBy": "Requested by",
    "skills.openLink": "Open Link",
    "skills.joinOnline": "Join Online",
    "skills.joinToGetLink": "Online session - join to get the link",
    "skills.online": "Online",
    "skills.offline": "Offline",
    "skills.inPerson": "In-person",
    "skills.interested": "interested",
    "skills.yourRequest": "Your request",
    "skills.yourSkill": "Your skill",
    "skills.offeredToHelp": "Offered to help",
    "skills.teachThis": "I can teach this!",
    "skills.locationPlaceholder": "Location (e.g. Community Hall, Park)",
    "skills.sessionLinkOptional": "Session link (Zoom, Google Meet, etc.) - optional",
    "skills.messageSent": "Message sent! Opening conversation...",

    // Login
    "login.loadCommunitiesFailed": "Failed to load communities.",
    "login.selectOrRequest": "Select an existing community or submit a valid community request.",
    "login.accountCreated": "Account created. You can now log in.",
    "login.accountAndRequest": "Account created and community request submitted.",
    "login.authFailed": "Authentication failed.",

    // Help
    "help.requestBlocked": "Request blocked: {reason}",
    "help.ownRequest": "This is your own request!",
    "help.onBehalfPlaceholder": "On behalf of (senior's name)",
    "help.messageRequester": "Message Requester",

    // Profile
    "profile.profileUpdated": "Profile updated!",
    "profile.contactRemoved": "Contact removed",
    "profile.allowFamilyView": "Allow family to view my activity",
    "profile.allowFamilyViewDesc": "Family members can see your check-ins, events & help requests",
    "profile.updateFailed": "Failed to update",
    "profile.familyViewingEnabled": "Family viewing enabled",
    "profile.familyViewingDisabled": "Family viewing disabled",
  },
  te: {
    // App
    "app.name": "సీనియర్‌స్ఫియర్",
    "app.tagline": "మీ సమాజంతో కనెక్ట్ అవ్వండి",
    "app.loading": "లోడ్ అవుతోంది...",
    "app.user": "వినియోగదారు",
    "app.friend": "మిత్రుడు",
    "app.anonymous": "అజ్ఞాత",
    "app.justNow": "ఇప్పుడే",
    "app.minutesAgo": "{count}ని క్రితం",
    "app.hoursAgo": "{count}గం క్రితం",
    "app.daysAgo": "{count}రోజుల క్రితం",

    // Roles
    "role.senior": "సీనియర్ సిటిజన్",
    "role.family_member": "కుటుంబ సభ్యుడు",
    "role.moderator": "కమ్యూనిటీ మోడరేటర్",
    "role.admin": "అడ్మినిస్ట్రేటర్",
    "role.badge.moderator": "మోడరేటర్",
    "role.badge.family": "కుటుంబం",
    "role.badge.admin": "అడ్మిన్",

    // Nav
    "nav.home": "హోమ్",
    "nav.dashboard": "డాష్‌బోర్డ్",
    "nav.community": "సమాజం",
    "nav.events": "ఈవెంట్‌లు",
    "nav.skills": "నైపుణ్యాలు",
    "nav.help": "సహాయం",
    "nav.messages": "సందేశాలు",
    "nav.helpRequests": "సహాయ అభ్యర్థనలు",
    "nav.profile": "ప్రొఫైల్",
    "nav.logout": "లాగ్ అవుట్",

    // Dashboard
    "dashboard.hello": "నమస్కారం",
    "dashboard.whatToDo": "ఈ రోజు మీరు ఏమి చేయాలనుకుంటున్నారు?",
    "dashboard.checkin": "రోజువారీ చెక్-ఇన్",
    "dashboard.checkedIn": "✓ ఈ రోజు చెక్-ఇన్ అయింది!",
    "dashboard.communityStats": "సమాజ గణాంకాలు",
    "dashboard.members": "సభ్యులు",
    "dashboard.upcomingEvents": "రాబోయే ఈవెంట్‌లు",
    "dashboard.helpRequests": "సహాయ అభ్యర్థనలు",
    "dashboard.skillsShared": "పంచుకున్న నైపుణ్యాలు",
    "dashboard.quickActions": "త్వరిత చర్యలు",
    "dashboard.createEvent": "ఈవెంట్ సృష్టించు",
    "dashboard.createEventDesc": "నడక లేదా సమావేశం ఏర్పాటు చేయండి",
    "dashboard.shareSkill": "నైపుణ్యం పంచు",
    "dashboard.shareSkillDesc": "మీకు తెలిసినది నేర్పించండి",
    "dashboard.askHelp": "సహాయం అడగండి",
    "dashboard.askHelpDesc": "సహాయం కోసం అభ్యర్థించండి",
    "dashboard.createPost": "పోస్ట్ చేయండి",
    "dashboard.createPostDesc": "సమాజంతో పంచుకోండి",
    "dashboard.viewEvents": "ఈవెంట్‌లు చూడండి",

    // Events
    "events.title": "ఈవెంట్‌లు",
    "events.create": "సృష్టించు",
    "events.noEvents": "ఇంకా ఈవెంట్‌లు లేవు",
    "events.noEventsDesc": "మీ సమాజం కోసం మొదటి ఈవెంట్ సృష్టించండి!",
    "events.createEvent": "ఈవెంట్ సృష్టించు",
    "events.eventTitle": "ఈవెంట్ శీర్షిక",
    "events.description": "వివరణ",
    "events.date": "తేదీ",
    "events.time": "సమయం (ఐచ్ఛికం)",
    "events.location": "ప్రదేశం",
    "events.cancel": "రద్దు",
    "events.joined": "చేరారు",
    "events.join": "చేరండి",
    "events.by": "ద్వారా",
    "events.attendees": "హాజరైనవారు",
    "events.remove": "తొలగించు",

    // Skills
    "skills.title": "నైపుణ్యాల మార్పిడి",
    "skills.offer": "నైపుణ్యం అందించు",
    "skills.noSkills": "ఇంకా నైపుణ్యాలు పంచలేదు",
    "skills.noSkillsDesc": "మొదట నైపుణ్యం పంచండి!",
    "skills.offerSkill": "నైపుణ్యం అందించు",
    "skills.skillTitle": "నైపుణ్యం శీర్షిక",
    "skills.description": "వివరణ",
    "skills.cancel": "రద్దు",
    "skills.learning": "నేర్చుకుంటున్నాను",
    "skills.learnThis": "ఇది నేర్చుకో",
    "skills.taughtBy": "నేర్పించేవారు",
    "skills.learners": "నేర్చుకునేవారు",
    "skills.remove": "తొలగించు",

    // Help
    "help.title": "సహాయ అభ్యర్థనలు",
    "help.create": "సహాయం అభ్యర్థించు",
    "help.noRequests": "సహాయ అభ్యర్థనలు లేవు",
    "help.noRequestsDesc": "అందరూ బాగున్నట్లు ఉంది!",
    "help.createRequest": "సహాయం అభ్యర్థించు",
    "help.whatHelp": "మీకు ఏ సహాయం కావాలి?",
    "help.category": "వర్గం",
    "help.urgency": "అత్యవసరత",
    "help.locationOpt": "ప్రదేశం (ఐచ్ఛికం)",
    "help.cancel": "రద్దు",
    "help.volunteer": "వాలంటీర్",
    "help.volunteered": "వాలంటీర్ అయ్యారు",
    "help.volunteers": "వాలంటీర్లు",
    "help.pending": "పెండింగ్",
    "help.assigned": "కేటాయించారు",
    "help.completed": "పూర్తయింది",
    "help.urgencyLow": "తక్కువ",
    "help.urgencyMedium": "మధ్యస్థం",
    "help.urgencyHigh": "అధికం",
    "help.catGeneral": "సాధారణం",
    "help.catMedical": "వైద్యం",
    "help.catTransport": "రవాణా",
    "help.catGroceries": "కిరాణా",
    "help.catTechnology": "సాంకేతికం",

    // Community
    "community.title": "సమాజం",
    "community.activity": "కార్యకలాపం",
    "community.flagged": "ఫ్లాగ్ చేయబడింది",
    "community.showAll": "అన్నీ చూపు",
    "community.shareSomething": "మీ సమాజంతో ఏదైనా పంచుకోండి...",
    "community.aiModeration": "🤖 AI మోడరేషన్ యాక్టివ్",
    "community.post": "పోస్ట్",
    "community.posting": "పోస్ట్ చేస్తోంది...",
    "community.noPosts": "ఇంకా పోస్ట్‌లు లేవు",
    "community.noPostsDesc": "మొదట ఏదైనా పంచుకోండి!",
    "community.noFlagged": "ఫ్లాగ్ చేసిన పోస్ట్‌లు లేవు",
    "community.healthy": "సమాజం ఆరోగ్యంగా ఉంది! 🎉",
    "community.report": "రిపోర్ట్",
    "community.dismissFlag": "✓ ఫ్లాగ్ తొలగించు",
    "community.remove": "తొలగించు",

    // Profile
    "profile.title": "ప్రొఫైల్",
    "profile.editProfile": "ప్రొఫైల్ మార్చు",
    "profile.save": "సేవ్ చేయి",
    "profile.cancel": "రద్దు",
    "profile.emergencyContact": "అత్యవసర సంప్రదింపు",
    "profile.contactName": "సంప్రదింపు పేరు",
    "profile.phone": "ఫోన్ నంబర్",
    "profile.emailOptional": "కుటుంబ సభ్యుల కనెక్షన్ కోసం ఇమెయిల్",
    "profile.relationship": "సంబంధం",
    "profile.saveContact": "సంప్రదింపు సేవ్ చేయి",
    "profile.familyMembers": "కుటుంబ సభ్యులు",
    "profile.connectedFamily": "కనెక్ట్ అయిన కుటుంబ సభ్యుడు",
    "profile.inviteDesc": "దిగువ ఆహ్వాన లింక్‌ను మీ కుటుంబ సభ్యుడితో పంచుకోండి. వారు మీ అత్యవసర సంప్రదింపులో సేవ్ చేసిన అదే ఇమెయిల్‌తో \"కుటుంబ సభ్యుడు\"గా సైన్ అప్ చేయాలి.",
    "profile.copyInvite": "ఆహ్వాన లింక్ కాపీ చేయి",
    "profile.moderatorInfo": "మోడరేటర్ సమాచారం",
    "profile.community": "సమాజం",
    "profile.role": "పాత్ర",
    "profile.familyInfo": "కుటుంబ సమాచారం",
    "profile.familyInfoDesc": "మీ ప్రొఫైల్ వివరాలు మీ కనెక్ట్ అయిన సీనియర్‌తో సమకాలీకరించబడ్డాయి.",
    "profile.settings": "సెట్టింగ్‌లు",
    "profile.noCommunity": "సమాజం లేదు",

    // Login
    "login.fullName": "పూర్తి పేరు",
    "login.email": "ఇమెయిల్",
    "login.password": "పాస్‌వర్డ్",
    "login.iAm": "నేను:",
    "login.joinCommunity": "సమాజంలో చేరండి",
    "login.communitySelectHelp": "ఉన్న సమాజాన్ని ఎంచుకోండి లేదా మీదిది లేకపోతే కొత్త సమాజాన్ని అభ్యర్థించండి.",
    "login.selectCommunity": "సమాజాన్ని ఎంచుకోండి",
    "login.requestNewCommunity": "కొత్త సమాజాన్ని అభ్యర్థించు",
    "login.communityName": "సమాజ పేరు (ఉదా. సన్‌రైజ్ రెసిడెన్సీ)",
    "login.city": "నగరం",
    "login.area": "ప్రాంతం / లోకాలిటీ",
    "login.additionalNotes": "అదనపు గమనికలు (ఐచ్ఛికం)",
    "login.communityRequestHelp": "అదే ప్రాంతం నుండి వచ్చిన సరిపోలే అభ్యర్థనలతో ఇది లెక్కించబడుతుంది. 5 అభ్యర్థనల తర్వాత అడ్మిన్ ఆమోదం మొదలవుతుంది.",
    "login.signUp": "సైన్ అప్",
    "login.logIn": "లాగిన్",
    "login.pleaseWait": "దయచేసి వేచి ఉండండి...",
    "login.alreadyAccount": "ఇప్పటికే ఖాతా ఉందా?",
    "login.noAccount": "ఖాతా లేదా?",
    "login.seniorDesc": "నేను కనెక్ట్ అవ్వాలనుకునే సీనియర్‌ని",
    "login.familyDesc": "నేను ప్రియమైన వారిని చూసుకోవాలనుకుంటున్నాను",
    "login.moderatorDesc": "నేను సమాజాన్ని నిర్వహించడంలో సహాయం చేస్తాను",

    // Emergency
    "emergency.title": "అత్యవసర సంప్రదింపు",
    "emergency.callNow": "ఇప్పుడు కాల్ చేయి",
    "emergency.cancel": "రద్దు",
    "emergency.familyDoctor": "కుటుంబ వైద్యుడు",
    "emergency.loading": "లోడ్ అవుతోంది...",
    "emergency.noContact": "అత్యవసర సంప్రదింపు లేదు",
    "emergency.addContact": "ప్రొఫైల్‌లో సంప్రదింపును జోడించండి",

    // Language
    "lang.switch": "English",

    // Header
    "header.toggleTheme": "థీమ్ మార్చు",
    "header.switchLanguage": "భాష మార్చు",
    "header.install": "ఇన్‌స్టాల్",
    "header.installApp": "యాప్ ఇన్‌స్టాల్ చేయి",
    "header.installDismissed": "ఇన్‌స్టాల్ ప్రాంప్ట్ మూసివేయబడింది.",

    // Notifications
    "notifications.title": "నోటిఫికేషన్‌లు",
    "notifications.markAllRead": "అన్నీ చదివినట్లు గుర్తించు",
    "notifications.noNotifications": "ఇంకా నోటిఫికేషన్‌లు లేవు",

    // Messages
    "messages.loading": "లోడ్ అవుతోంది...",
    "messages.loginRequired": "సందేశాలు చూడటానికి లాగిన్ చేయండి.",
    "messages.empty": "ఇంకా సందేశాలు లేవు.",
    "messages.emptyHello": "ఇంకా సందేశాలు లేవు. హాయ్ చెప్పండి!",
    "messages.emptyHint": "నైపుణ్యాలు, ఈవెంట్‌లు లేదా సహాయ అభ్యర్థనల ద్వారా మీరు ఎవరితోనైనా కనెక్ట్ అయినప్పుడు సందేశాలు ఇక్కడ కనిపిస్తాయి.",
    "messages.typePlaceholder": "సందేశం టైప్ చేయండి...",
    "messages.contextSkill": "నైపుణ్యం",
    "messages.contextHelpRequest": "సహాయ అభ్యర్థన",
    "messages.contextEvent": "ఈవెంట్",

    // Speech
    "speech.readAloud": "చదివి వినిపించు",
    "speech.stop": "ఆపు",
    "speech.voiceInput": "గొంతు ద్వారా టైప్ చేయి",
    "speech.listening": "వింటున్నాను...",

    // Common
    "common.edit": "మార్చు",
    "common.save": "సేవ్ చేయి",
    "common.saved": "సేవ్ అయింది!",
    "common.cancel": "రద్దు",

    // Not found
    "notFound.message": "అయ్యో! పేజీ దొరకలేదు",
    "notFound.home": "హోమ్‌కి వెళ్ళండి",

    // Admin
    "admin.loading": "అడ్మిన్ డాష్‌బోర్డ్ లోడ్ అవుతోంది...",
    "admin.refreshed": "డాష్‌బోర్డ్ రిఫ్రెష్ అయింది.",
    "admin.loadFailed": "అడ్మిన్ డాష్‌బోర్డ్ లోడ్ చేయలేకపోయాము.",
    "admin.communityApproved": "సమాజం ఆమోదించబడింది మరియు మోడరేటర్ సృష్టించబడ్డారు.",
    "admin.approveFailed": "అభ్యర్థనను ఆమోదించలేకపోయాము.",
    "admin.communityRejected": "సమాజ అభ్యర్థన తిరస్కరించబడింది.",
    "admin.rejectFailed": "అభ్యర్థనను తిరస్కరించలేకపోయాము.",
    "admin.moderatorReassigned": "మోడరేటర్ మళ్లీ కేటాయించబడ్డారు.",
    "admin.reassignFailed": "మోడరేటర్‌ను మళ్లీ కేటాయించలేకపోయాము.",
    "admin.replacementCreated": "ప్రత్యామ్నాయ మోడరేటర్ సృష్టించబడ్డారు.",
    "admin.replacementFailed": "ప్రత్యామ్నాయ మోడరేటర్‌ను సృష్టించలేకపోయాము.",
    "admin.communityDeleted": "{community} తొలగించబడింది.",
    "admin.deleteFailed": "సమాజాన్ని తొలగించలేకపోయాము.",
    "admin.copied": "{label} కాపీ అయింది.",
    "admin.copyFailed": "{label} కాపీ చేయలేకపోయాము.",
    "admin.title": "అడ్మిన్ డాష్‌బోర్డ్",
    "admin.subtitle": "సమాజాలు, వినియోగదారులు మరియు ప్లాట్‌ఫారమ్ సెట్టింగ్‌లను నిర్వహించండి",
    "admin.refresh": "రిఫ్రెష్",
    "admin.totalCommunities": "మొత్తం సమాజాలు",
    "admin.totalUsers": "మొత్తం వినియోగదారులు",
    "admin.pendingRequests": "పెండింగ్ అభ్యర్థనలు",
    "admin.communityRequestsTitle": "సమాజ అభ్యర్థనలు",
    "admin.noPendingRequests": "పెండింగ్ సమాజ అభ్యర్థనలు లేవు.",
    "admin.peopleRequested": "{count} మంది అభ్యర్థించారు",
    "admin.approve": "ఆమోదించు",
    "admin.reject": "తిరస్కరించు",

    // Skills
    "skills.requestSkill": "నైపుణ్య అభ్యర్థన",
    "skills.joined": "చేరారు ✓",
    "skills.failed": "విఫలమైంది: ",
    "skills.ownListing": "ఇది మీ స్వంత లిస్టింగ్!",
    "skills.alreadyJoined": "ఇప్పటికే చేరారు!",
    "skills.request": "అభ్యర్థన",
    "skills.offeredTab": "అందించిన నైపుణ్యాలు",
    "skills.requestsTab": "నైపుణ్య అభ్యర్థనలు",
    "skills.requestFormTitle": "నైపుణ్యం అభ్యర్థించండి",
    "skills.requestTitlePlaceholder": "మీరు ఏ నైపుణ్యం నేర్చుకోవాలనుకుంటున్నారు?",
    "skills.requestDescPlaceholder": "మీరు ఏమి నేర్చుకోవాలనుకుంటున్నారో వివరించండి...",
    "skills.submitRequest": "అభ్యర్థన సమర్పించు",
    "skills.noRequests": "ఇంకా నైపుణ్య అభ్యర్థనలు లేవు",
    "skills.noRequestsDesc": "మీరు నేర్చుకోవాలనుకునే నైపుణ్యాన్ని ముందుగా అభ్యర్థించండి!",
    "skills.requestBadge": "నైపుణ్య అభ్యర్థన",
    "skills.offeredBadge": "అందించిన నైపుణ్యం",
    "skills.requestedBy": "అభ్యర్థించిన వారు",
    "skills.openLink": "లింక్ తెరువు",
    "skills.joinOnline": "ఆన్‌లైన్‌లో చేరండి",
    "skills.joinToGetLink": "ఆన్‌లైన్ సెషన్ - లింక్ పొందడానికి ముందుగా చేరండి",
    "skills.online": "ఆన్‌లైన్",
    "skills.offline": "ఆఫ్‌లైన్",
    "skills.inPerson": "ప్రత్యక్షంగా",
    "skills.interested": "ఆసక్తి ఉన్నవారు",
    "skills.yourRequest": "మీ అభ్యర్థన",
    "skills.yourSkill": "మీ నైపుణ్యం",
    "skills.offeredToHelp": "సహాయం చేయడానికి ముందుకు వచ్చారు",
    "skills.teachThis": "నేను ఇది నేర్పగలను!",
    "skills.locationPlaceholder": "ప్రదేశం (ఉదా. కమ్యూనిటీ హాల్, పార్క్)",
    "skills.sessionLinkOptional": "సెషన్ లింక్ (జూమ్, గూగుల్ మీట్ మొదలైనవి) - ఐచ్ఛికం",
    "skills.messageSent": "సందేశం పంపబడింది! సంభాషణ తెరుస్తోంది...",

    // Login
    "login.loadCommunitiesFailed": "సమాజాలను లోడ్ చేయలేకపోయాము.",
    "login.selectOrRequest": "ఉన్న సమాజాన్ని ఎంచుకోండి లేదా చెల్లుబాటు అయ్యే సమాజ అభ్యర్థనను సమర్పించండి.",
    "login.accountCreated": "ఖాతా సృష్టించబడింది. మీరు ఇప్పుడు లాగిన్ చేయవచ్చు.",
    "login.accountAndRequest": "ఖాతా సృష్టించబడింది మరియు సమాజ అభ్యర్థన సమర్పించబడింది.",
    "login.authFailed": "ప్రమాణీకరణ విఫలమైంది.",

    // Help
    "help.requestBlocked": "అభ్యర్థన నిలిపివేయబడింది: {reason}",
    "help.ownRequest": "ఇది మీ స్వంత అభ్యర్థన!",
    "help.onBehalfPlaceholder": "తరఫున (సీనియర్ పేరు)",
    "help.messageRequester": "అభ్యర్థించిన వ్యక్తికి సందేశం",

    // Profile
    "profile.profileUpdated": "ప్రొఫైల్ అప్‌డేట్ అయింది!",
    "profile.contactRemoved": "సంప్రదింపు తొలగించబడింది",
    "profile.allowFamilyView": "నా కార్యకలాపాలు కుటుంబానికి చూపించు",
    "profile.allowFamilyViewDesc": "కుటుంబ సభ్యులు మీ చెక్-ఇన్‌లు, ఈవెంట్‌లు మరియు సహాయ అభ్యర్థనలను చూడగలరు",
    "profile.updateFailed": "అప్‌డేట్ చేయలేకపోయాము",
    "profile.familyViewingEnabled": "కుటుంబ వీక్షణ ప్రారంభించబడింది",
    "profile.familyViewingDisabled": "కుటుంబ వీక్షణ నిలిపివేయబడింది",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("app_language") as Language) || "en";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app_language", lang);
  }, []);

  const t = useCallback(
    (key: string) => translations[language][key] || translations.en[key] || key,
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
